#!/bin/bash

#Colors
RED='\e[1;31m'
BLUE='\e[1;34m'
GREEN='\e[1;32m'
NC='\033[0m' # No Color

printf "${BLUE}\n"
printf "   _  _       _            ___  ___ \n"
printf "  /_\| |_ _ _(_)_  _ _ __ |   \| _ )\n"
printf " / _ \  _| '_| | || | '  \| |) | _ \\ \n"
printf "/_/ \_\__|_| |_|\_,_|_|_|_|___/|___/\n"                          
printf "${NC}\n"
printf "Server Version: ${GREEN}1.1.0${NC}\n"
POSITIONAL_ARGS=()

#set defaults
UVICORN_NUM_WORKERS=1

while [[ $# -gt 0 ]]; do
  case $1 in
    --wal-writer)
      WAL_WRITER=1
      shift # past argument
      ;;
    --tsc-gen)
      TSC_GEN=1
      shift # past argument
      ;;
    --rest-api)
      API=1
      shift # past argument
      ;;
    --uvicorn-num-workers)
      UVICORN_NUM_WORKERS=$2
      shift # past argument
      shift # past argument
      ;;
    -h|--help)
      HELP=YES
      shift # past argument
      ;;
    -*|--*)
      echo "Unknown option $1"
      exit 1
      ;;
    *)
      POSITIONAL_ARGS+=("$1") # save positional arg
      shift # past argument
      ;;
  esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

if [[ "$WAL_WRITER" -eq 1 ]]; then
  printf "Starting Service: ${RED}WAL Writer...${NC}\n"
  exec python ./wal_writer/main.py
elif [[ "$TSC_GEN" -eq 1 ]]; then
  printf "Starting Service: ${RED}TSC Generator...${NC}\n"
  exec python ./tsc_generator/src/main.py
elif [[ "$API" -eq 1 ]]; then
  printf "Starting Service: ${RED}REST API...${NC}\n"
  exec uvicorn rest_api.main:app --proxy-headers --workers $UVICORN_NUM_WORKERS --host 0.0.0.0 --port 80 --ws-per-message-deflate False
else 
  HELP=YES
fi