
services:
  tsc-generator:
    image: atriumdb/atriumdb-server:1.1.0
    command: ./atriumdb-server --tsc-gen
#    restart: always
    # set internal path you want tsc and wal files to sit at. Also mount code directory so its easy to change without
    # container rebuild. Format is host/path:container/path
    volumes:
      - ../../tsc_generator:/src/tsc_generator
      - ./data/tsc:/data/tsc
      - ./data/wal:/data/wal
      - ../config_example.yaml:/config.yaml
      - ../secrets_example.yaml:/secrets.yaml
    depends_on:
      mariadb:
        condition: service_healthy

  wal-writer:
    image: atriumdb/atriumdb-server:1.1.0
    command: ./atriumdb-server --wal-writer
    # Set internal path where you want wal files stored format is host/path:container/path
    volumes:
      - ../../wal_writer:/src/wal_writer
      - ./data/wal:/data/wal
      - ../config_example.yaml:/config.yaml
      - ../secrets_example.yaml:/secrets.yaml
    #    restart: always
    depends_on:
      rabbitMQ:
        condition: service_healthy
      mariadb:
        condition: service_healthy
      siridb:
        condition: service_healthy

  atriumdb-api:
    image: atriumdb/atriumdb-server:1.1.0
    command: ./atriumdb-server --rest-api --uvicorn-num-workers 1
    env_file:
      - ../example_api.env
    ports:
      - 89:80
    volumes:
      - ../../rest_api:/src/rest_api
      - ./data/tsc:/data/tsc
    depends_on:
      mariadb:
        condition: service_healthy
      siridb:
        condition: service_healthy

  # if you want bundled rabbitMQ container
  rabbitMQ:
    image: rabbitmq:3-management
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s
    restart: always
    ports:
      - 5672:5672
      - 15672:15672

  siridb:
    image: ghcr.io/siridb/siridb-server:latest
    ports:
      - 127.0.0.1:8080:8080
      - 9000:9000
      - 127.0.0.1:9080:9080
    volumes:
      - ./data/siridb:/var/lib/siridb
    environment:
      SIRIDB_OPTIMIZING_INTERVAL: 3600
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:8080/healthy"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s
    restart: always

  mariadb:
    image: mariadb:latest
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_MYSQL_LOCALHOST_USER: 1
      MARIADB_PASSWORD: maria
      MARIADB_USER: maria
      MARIADB_DATABASE: atriumdb-dev
    ports:
      - 3306:3306
    healthcheck:
      test: /usr/local/bin/healthcheck.sh --su mysql --connect
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 0s

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8090:8080