name: atriumdb_server_release_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger: none

pool:
  vmImage: ubuntu-20.04

parameters:
  - name: releaseVersion
    displayName: Release Version
    type: string

stages:
- stage: Build
  jobs:
    - job: build_docker_image
      displayName: Build Docker Image

      steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'DockerHub AttriumDB'
          repository: 'atriumdb/atriumdb-server'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: '${{ parameters.releaseVersion }}'